### ISSUE TITLE
Compiling for older GLIBC versions

### ISSUE THREAD

**Issue by jeanbmar** [frida/docker-images#1]
Hello,

First, thank you very much for this repo, it makes compiling much easier.
Unfortunately, it doesn't help with my issue since the containers use GLIC 2.35 :).

I've been trying to use Frida Gadget on AWS Lambda for some time, but it's not simple.
AWS Lambda uses the Amazon Linux 2 OS, which is derived from RHEL I think, and currently using GLIBC 2.26...
I've tried to compile from Amazon Linux 2 without success. Amazon doesn't provide binaries to build arm64 targets and the official repo for this sytem use older gcc versions.
 
I've noticed Gadget from the main repo releases is built for GLIBC 2.27, so it might not be that far.

Before I give it a try, do you think it's technically possible to compile for 2.26? Do you have advice to share?

Thanks!

**Comment by oleavr** [comment]
Hey,

The Docker images in this repo are based on Ubuntu 22.04, and thus glibc 2.35, however: each image contains a toolchain that targets glibc 2.5. It lives in `/opt/x-tools`. The Docker container sets up `CC`, `CXX`, etc. So basically using these images you can build portable binaries that run on glibc >= 2.5 -- just make sure you build with `-static-libgcc` (plus `-static-libstdc++` for C++).

Cheers!

**Comment by jeanbmar** [comment]
Fantastic thank you!
